# Generated by Django 3.0.1 on 2019-12-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('created_at',)},
        ),
    ]
